
# successfully retrieve movie with id
GET http://localhost:8080/movies/1

###

# successfully retrieve movie with title
GET http://localhost:8080/movies?title=First

###

# fail to retrieve movie with id
GET http://localhost:8080/movies/100

###

# fail to retrieve movie with id
GET http://localhost:8080/movies/a

###

# save a movie / send at least 2x to fail saving
POST http://localhost:8080/movies
Content-Type: application/json

{
  "title": "Movie title"
}

###

# fail to save => no title
POST http://localhost:8080/movies
Content-Type: application/json

{
  "id": 0,
  "title": "  "
}