
# successfully retrieve movie with id
GET http://localhost:8080/movies/1

###

# successfully retrieve movie with title
GET http://localhost:8080/movies?title=First

###

# fail to retrieve movie with id
GET http://localhost:8080/movies/100

###

# fail to retrieve movie with id
GET http://localhost:8080/movies/a